/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/logo.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.website.geometry}
        material={materials['default']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.26}
      />
    </group>
  )
}

useGLTF.preload('/logo.glb')
